extends:
  - '@commitlint/config-conventional'
rules:
  body-max-line-length:
    - 2
    - always
    - 500
  subject-case:
    - 1
    - never
    - - upper-case
      - pascal-case
      - start-case
