branches:
  - main
ci: false
plugins:
  [
    [
      "@semantic-release/commit-analyzer",
      { "releaseRules": [{ "scope": "no-release", "release": "minor" }] },
    ],
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    ["@semantic-release/npm", { "npmPublish": false }],
    [
      "@semantic-release/exec",
      {
        "prepareCmd": 'echo "version: ${nextRelease.version}" && echo ${nextRelease.version} > .version',
      },
    ],
    [
      "@semantic-release/git",
      {
        "assets": ["package.json", "package-lock.json", "CHANGELOG.md", ".version"],
        "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}",
      },
    ],
  ]
